% This script is inititialization script for receiver. This has to be run before receiver_script.m
% Script initializes hardware settings.
% Some of these settings you can change from receiver_script.m in the section "Device parameters", 
% but it is easier for example to design custom filter only once, than every time you run receiver_script.m
% If you wish to design your own custom filter, uncomment last line in this script and change
% 'UseCustomFilter' to true.
% WARNING: Designing custom filter could couse wrong demodulation

% Device parameters
device = 'AD936x';                              %device used for object initialization
ip = '192.168.3.2';                             %ip address of device
CenterFrequency = 2.4e9;                        %RF center frequency
RadioBasebandRate = 1e6;                        %RF bandwidth
RadioFrameLength = 900e3;                       %samples per frame (must be divideable by 60)

%object initialization
rx_obj = sdrrx( device, ...
            'IPAddress',        ip, ...
            'CenterFrequency',  CenterFrequency, ...
            'BasebandSampleRate', RadioBasebandRate,...
            'GainSource', 'Manual', ...
            'SamplesPerFrame', RadioFrameLength, ...
            'ChannelMapping',  1, ...
            'OutputDataType',   'double', ...
            'ShowAdvancedProperties', true, ...
            'UseCustomFilter', false, ...
            'Gain', 10, ...
            'BISTLoopbackMode', 'Disabled');

% rx_obj.designCustomFilter();
            
